# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e044f0c647d9880fded659fa1233ad05cf17b537724a6545879823fa7f08d0d6acf606e3e7d978fd011923bd03c2cdd82ad8f169db77617443c2ae088d49928c

test:
  secret_key_base: 5708e1b02266f640e8e0d68aad60c3ba1f847172110164ac71f736ce1f2bea1c2d0e6fa122598a14ad48c0b6ff605f9bf238fb3ca56521d4dd19c6cc66459b09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
